# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-22 01:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='İsim')),
                ('content', models.TextField(verbose_name='Yorum')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esnaf', models.CharField(blank=True, max_length=30, null=True, verbose_name='İlgili Tezgah Elemanı')),
                ('alımad', models.CharField(blank=True, max_length=30, null=True, verbose_name='Alım yapılan kişinin Adı-Soyadı')),
                ('alımtc', models.IntegerField(blank=True, null=True, verbose_name='Alım yapılan kişinin TC Kimlik No')),
                ('title', models.IntegerField(blank=True, null=True, verbose_name='Seri No')),
                ('titleiki', models.CharField(blank=True, max_length=120, null=True, verbose_name='Model')),
                ('titleuc', models.IntegerField(blank=True, null=True, verbose_name='Alınan Fiyat')),
                ('content', models.TextField(blank=True, max_length=200, null=True, verbose_name='İçerik')),
                ('publishing_date', models.DateTimeField(auto_now_add=True, verbose_name='yayımlanma_tarihi')),
                ('satış_date', models.DateTimeField(auto_now_add=True, verbose_name='Değişim tarihi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Fotoğraf')),
                ('tezgahfiyatı', models.IntegerField(blank=True, null=True, verbose_name='Tezgah Fiyatı')),
                ('kacasatıldı', models.IntegerField(blank=True, null=True, verbose_name='Kaça Satıldığı')),
                ('kazanc', models.IntegerField(blank=True, null=True, verbose_name='Kazanç')),
                ('slug', models.SlugField(editable=False, max_length=130, unique=True)),
                ('confirm', models.NullBooleanField(verbose_name='Yayımlansınmı?')),
                ('contente', models.TextField(blank=True, max_length=200, null=True, verbose_name='Emanetci hakkındaki bilgiler..')),
                ('contenth', models.TextField(blank=True, max_length=200, null=True, verbose_name='Hurda da ne için kullanılır..')),
                ('contents', models.TextField(blank=True, max_length=200, null=True, verbose_name='Satın alan kişi hakkında bilgi..')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
            ],
            options={
                'ordering': ['-publishing_date'],
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='post.Post'),
        ),
    ]
